name: flutterforge
description: A Flutter CLI tool for creating projects with interactive prompts.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

# Export the main library
flutterforge_cli:
  main: lib/flutterforge_cli.dart


