name: flutterforge
description: A Flutter CLI tool for creating projects with interactive prompts.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  path: ^1.9.1
  http: ^1.2.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3

# Export the main library
flutterforge_cli:
  main: lib/flutterforge_cli.dart


