include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    unnecessary_null_comparison: ignore
    invalid_annotation_target: ignore
    constant_identifier_names: ignore
  exclude:
    - bricks/**
    - '**/*.arb'
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - 'lib/application/generated/**'
    - 'lib/application/l10n/**.dart'
    - 'test/**'

linter:
  rules:
    always_specify_types: true
    prefer_expression_function_bodies: true
    always_declare_return_types: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: true
