name: Test Workflow

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Test PR Info
        run: |
          echo "PR Number: ${{ github.event.pull_request.number }}"
          echo "PR Title: ${{ github.event.pull_request.title }}"
          echo "PR State: ${{ github.event.pull_request.state }}"
          echo "PR Merged: ${{ github.event.pull_request.merged }}"
          echo "Event Type: ${{ github.event_name }}"
          echo "Event Action: ${{ github.event.action }}"
      
      - name: Success Message
        run: |
          echo "✅ Test workflow executed successfully!"
          echo "This confirms GitHub Actions is working properly." 